.github/workflows/build-and-publish.yml, .gitignore, Dockerfile, README.md, api.py, docker-compose.yml, ui.py, utils.sh
We should make it as simple as possible for people to run WAS. Right now, people need to clone a git repo, run multiple commands and create a .env file. With the changes in this PR, people can run the published container image with a single command. A persistent volume to keep the user_*.json files will automatically be created, so settings will survive restarting/updating containers.
Tested with `docker run ..` and `./utils.sh`. To test before merge, use the feature-storage_dir tag:
```
docker run --rm -it --env=OTA_URL="http://my_was_host:8502/static/ota.bin" --network=host --volume=was-storage:/app/storage ghcr.io/toverainc/willow-application-server:feature-storage_dir
```
=> Improvements to run using published container image

README.md
The command to start the WAS container uses willow-application-server as container name. Let's be consistent and use the same in the command to copy the Willow binary to the container to avoid confusion.
=> README: use same container name in commands

api.py, ui.py
When calling the /api/nvs/save API via curl, we were seeing the following stack trace:
willow-application-server-was-1  |   File "/app/api.py", line 345, in save_nvs
willow-application-server-was-1  |     await post_nvs(request, False)
willow-application-server-was-1  |   File "/app/api.py", line 202, in post_nvs
willow-application-server-was-1  |     save_json_to_file(STORAGE_USER_NVS, data)
willow-application-server-was-1  |   File "/app/api.py", line 212, in save_json_to_file
willow-application-server-was-1  |     config_file.write(content)
willow-application-server-was-1  | TypeError: write() argument must be str, not dict
This is because we're JSON serializing the json argument to shared.post_nvs(). In shared.post_nvs(), we're passing the json argument to reequests.post() as a json …
=> treewide: fix double JSON serialization

requirements.txt
This requires AnyIO >= 3.7.1 <= 4.0.0, so bump AnyIO to 3.7.1.
With v0.100.2, Pydantic v2 support was introduced. Its core was re-written in Rust and should improve performance.
=> requirements: bump FastAPI to 0.103.1

ui.py
Ideally we want to only show non-pre releases by default, and in that case we wouldn't have to do this, but as we don't have a final release right now, let's make sure we select the release marked as latest Github by default in the OTA dropdown.
=> ui: select latest release by default

command_endpoints/rest.py
Python requests (by default) has no timeout. This can cause WAS to hang indefinitely waiting for a REST response. Set a connect timeout of 1s which will speedily address connection failures for blatantly misconfigured REST endpoints. Also set final response timeout to 30 seconds which is still long but plenty of time for an LLM, etc to respond.
=> Increase final response timeout to 30 seconds for REST endpoint

Dockerfile, requirements.txt
Wheels for uvloop are now available, so let's add uvloop to requirements.txt to avoid it being built.
This greatly reduces the container image build time.
=> container: use uvloop wheel

api.py
We first check if data contains hostname, but then we overwrite data with get_nvs which does not contain hostname, so if we hit an exception later, the call to log.error causes another exception.
As we're copying data['hostname'] to hostname before overriding data, we should print the hostname variable instead.
This avoids the following exception during handling of another exception:
```
[2023-10-25T13:52:39] INFO:     10.0.2.100:45554 - 'POST /api/config?type=nvs&apply=1 HTTP/1.1' 500 Internal Server Error
[2023-10-25T13:52:39] ERROR:    Exception in ASGI application
Traceback (most recent call last):
File "/app/api.py", line 400, in post_nvs
await ws.send_text(msg)
File "/usr/local/lib/python3.12/site-packages/starlette/websockets.py", line 163, in send_text
await self.send({"type": …
```
=> api: fix exceptions in post_config, post_nvs

app/internal/command_endpoints/mqtt.py
The cb_disconnect function lacks the self argument.
Silences the following flake8 errors:
app/internal/command_endpoints/mqtt.py:95:9: F821 undefined name 'self'
app/internal/command_endpoints/mqtt.py:96:9: F821 undefined name 'self'
Fixes: 571cf763b0db ("command_endpoints: add connected boolean to MqttEndpoint")
=> command_endpoints: fix cb_disconnect in MqttEndpoint

app/internal/command_endpoints/__init__.py
A command endpoint that inserts newlines in the speech result causes the result to be printed outside of the display. We do not want to deal with this in the Willow C code, and as we will eventually make WAS command mode the default and rip out endpoint support from Willow, we can simply do this in WAS.
As we're using a pydantic model for the command endpoint result, we can easily do this with a sanitize function in the CommandEndpointResult model, and call this when we initialize the CommandEndpointResponse. We can't do it when we initialize the CommandEndpointResult, as we sometimes change the speech attribute after init.
=> command_endpoints: sanitize result

requirements.txt
Fixes CVE-2023-45803 (moderate).
=> requirements: bump urllib3 to 2.0.7

default_config.json
We've had several reports of TTS not working. This was often because the user did not enable TTS audio responses. Let's make it the default to avoid more such reports in the future.
=> default_config: set audio response to TTS by default

app/routers/release.py
The release API router uses the /api prefix so we must not add it in routes.
Fixes: eedfa7c3624e ("app: move POST /api/release to app.routers.release")
=> routers.release: fix api_post_release path

app/internal/wake.py
With a WakeSession timeout of 200ms, some people frequently experience double wakes. Testing has shown that 400ms greatly reduces those double wakes, and does not introduce other issues.
Let's make 400ms the default.
=> wake: increase WakeSession timeout

.github/workflows/build-and-publish.yml
The maximum access for pull requests from public forked repositories for the packages scope is read, so we can not push a container to GHCR in a workflow triggered by a pull request from a fork. Fortunately this is not an issue here, as we just want CI to test if building WAS fails or not. The container image will be pushed once the PR is merged in the base branch.
Only push the container image for push events so pull requests from forks will not fail with 403.
=> CI: don't push container on pull request

.github/workflows/build-and-publish.yml
Dependabot updates create a local branch and trigger a push event. Because of this, we're still trying to push the container image to GHCR. As Dependabot push events are treated as they come from a fork, they receive a read-only GITHUB_TOKEN and thus are not able to push the container image and the workflow still fails with 403.
Skip push when github.actor is 'dependabot[bot]' to avoid this.
=> CI: don't push container image for dependabot updates

Dockerfile
This is not ideal, but it's the easiest way to fail pull requests if the tests fail.
=> Dockerfile: run pytest

Dockerfile
This is the current most recent version in the 3.12 release.
=> Dockerfile: bump base container to 3.12.9

.github/workflows/build-and-publish.yml, Dockerfile
Now that WAS-UI CI publishes a container image on push to main and release branches, and when pushing a tag, we can always include it in the WAS container image using COPY --from.
=> CI: always include UI in container image

Dockerfile
Let's use Alpine as base container to produce smaller images.
=> Docker: use Alpine base container

entrypoint.sh
Alpine doesn't have bash installed by default. Switch to sh to fix the following error during startup:
env: can't execute 'bash': No such file or directory
Fixes: 4b49d31cbad9 ("Docker: use Alpine base container")
=> Docker: use sh in entrypoint

requirements.txt
This is the current most recent version of pydantic.
Also bump dependencies that are causing conflicts.
Fixes CVE-2024-3772 (moderate).
Closes: #91
=> requirements: bump pydantic to 2.11.1

requirements.txt
As FastAPI is the core of Willow Application Server, this bump has been done in some incremental steps. This makes it easier to bisect potential issues. Each step has received some basic testing.
=> Bump FastAPI to 0.115.12

app/internal/command_endpoints/ha_rest.py, app/internal/command_endpoints/ha_ws.py
It appears certain intents (e.g. HassNeverMind (en) ) return a speech object that does not contain a plain text element.
This resulted in errors in the log such as:
as-1  | 2025-04-08 19:56:31 INFO     WAS Home Assistant WebSocket Endpoint: exception occurred: 'plain'
The Home Assistant documentation also suggests that returning SSML is a possibility too (https://developers.home-assistant.io/docs/intent_conversation_api#speech)
This fix means if there is no plain speech element returned, the code will now return an empty string to Willow, and will no longer error.
=> command_endpoints: handle missing speech responses from HomeAssistant

requirements.txt
This requires h11 and httpx to be bumped. Bump both of them to the current most recent version.
Closes: #100
=> requirements: bump httpcore to 1.0.9

.github/workflows/build-and-publish.yml, .gitignore, app/internal/was.py, utils.sh
WAS fetches timezone info from the Willow CF Worker at startup. The tz.json file generated by the gen-tz.py script is not used anymore.
=> treewide: remove gen-tz.py script

app/internal/command_endpoints/ha_rest.py, app/internal/command_endpoints/ha_ws.py, app/internal/command_endpoints/mqtt.py, app/internal/command_endpoints/openhab.py, app/internal/command_endpoints/rest.py, app/main.py
Get Willow device_id from the Home Assistant integration (https://github.com/ciaranj/ha_willow_integration) and add it when sending a command to Home Assistant over WebSocket. With this, Willow supports area awareness!
=> HA WS endpoint: get/send device_id from HA integration

Dockerfile, README.md
Fixes the following error in CI:
buildx failed with: ERROR: failed to solve: failed to parse stage name "ghcr.io/HeyWillow/willow-application-server-ui:main": invalid reference format: repository name (HeyWillow/willow-application-server-ui) must be lowercase
=> Docker: organization in container image URL should be lowercase

.github/workflows/build-and-publish.yml
This is best practice.
Reported-by: CodeQL
=> CI: set permissions on job

app/routers/release.py
CodeQL reports a possible SSRF due to not validating willow_url in the POST data. As this API endpoint is currently not used, just remove the cache action entirely rather than implementing validation.
Release caching happens automatically in GET /api/ota anyway, and if anything/anyone was actually using this we can always add it back.
=> routers.release: drop cache action from POST /api/release

.github/dependabot.yml
Dependabot opened separate PRs for pydantic and pydantic-core. They both failed due to dependency conflict. This is an attempt to have dependabot group updates to both packages together.
=> CI: group pydantic and pydantic-core updates

app/main.py
When WAS command mode is disabled, init_command_endpoint doesn't always throw an exception, so we don't always set app.command_endpoint. This can result in the follow exception in the WebSocket loop:
was[2448155]: 2025-04-30 07:57:50 ERROR    unhandled exception in WebSocket route: 'FastAPI' object has no attribute 'command_endpoint'
This in turn can result in a connection not being cleaned up from connmgr and possibly a duplicate client in it. If this happens, we're seeing the following error again while trying to send a command to a Willow:
RuntimeError: Unexpected ASGI message 'websocket.send', after sending 'websocket.close'.
Always initialize app.command_endpoint to None to fix this.
=> main: always initialize app.command_endpoint to None
